name: EliteLevelSync
version: '${project.version}'
main: fr.nathanmmo.elitelevelsync.EliteLevelSync
api-version: '1.21'
description: Synchronise le niveau requis EliteMobs avec mcMMO / ValhallaMMO / MMOCore
author: NathanMMO
softdepend: [EliteMobs, mcMMO, ValhallaMMO, MMACore]
commands:
  elsreload:
    description: Recharge la config
    permission: elitelevelsync.reload
    usage: /elsreload
permissions:
  elitelevelsync.reload: { description: Recharge la config, default: op }
  elitelevelsync.bypass: { description: Ignore la restriction, default: false }
