name: EliteLevelSync
version: 1.0.0
main: fr.zansekai.elitelevelsync.EliteLevelSync
api-version: '1.21'
authors: [Zansekai]
description: Synchronise les niveaux mcMMO vers les skills EliteMobs

depend: [mcMMO, EliteMobs]

commands:
  elitelevelsync:
    description: Commandes EliteLevelSync
    aliases: [els]
    usage: /els <reload|sync <joueur>>
    permission: elitelevelsync.admin
